### PR TITLE
Updated german translation and README

### PR DESCRIPTION
**Pull request by ghost**
Cheers! :)

### CODE REVIEW

**Comment by tofi86** [comment]
any chance to get that merged into your master?

**Comment by resilva** [comment]
I've merged the issue just right now, sorry for the long time without reply i haven't time and competence anymore to maintain this plugin. Also this plugin is for an old version of redmine.

**Comment by tofi86** [comment]
hey, good to know...
any chance you could note that in README.md or project description so that everyone knows that this project is inactive?
however - plugin works fine in 2.3 as far as I know...

**Comment by tofi86** [comment]
oops, seems as if I overread the first line in README. sorry :/

**Pull request merged**
